### ISSUE TITLE
User Coupons Popup

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#170] opened 2016-07-07 23:59 UTC
This didn't used to be a dialog, all of a sudden it's appearing as so.

<img width="482" alt="screen shot 2016-07-08 at 00 58 29" src="https://cloud.githubusercontent.com/assets/309336/16673566/24959a32-44a7-11e6-8021-9c864a978ef8.png">

**Comment by simonmorley** [comment] 2016-07-08 00:01
If it needs to be a popup, please remove the card. However, I think it need to be put back to a pure card.

@ZakMooney Could you have a look through the commits and see what you can find out please.

**Comment by ZakMooney** [comment] 2016-07-11 11:05
Not able to find a coupon dialog like that
However did find that a duplicate of the dialog for adding a new credit card was added to the Coupon & Discount codes section, which was causing the massive white space under the coupons and discount codes card

**Closed** 2016-07-11 12:16 UTC
