### ISSUE TITLE
Alerting devices page not using location slug

### ISSUE THREAD

**Issue by simonmorley** [cucumber-tony/cucumber-frontend#426] opened 2016-11-25 01:18 UTC
Open the list of alerting devices from the dashboard.

Click the device link.

You'll notice the slug is missing. Update link accordingly.

![screen_shot_2016-11-25_at_01_16_16](https://cloud.githubusercontent.com/assets/309336/20612036/25b25472-b2ad-11e6-8a4f-7b6e7a8a856d.png)

**Comment by ZakMooney** [comment] 2016-11-25 10:18
Duplicate of issue #241

**Closed** 2016-11-25 10:19 UTC
